/**
 * Report Settings Service
 * Manage report header/footer configuration
 */

const STORAGE_KEY = 'pacs_report_settings';

/**
 * Report Types
 */
export const REPORT_TYPES = {
  MEDICAL: 'medical',
  STATISTICAL: 'statistical',
  ADMINISTRATIVE: 'administrative',
  CUSTOM: 'custom'
};

/**
 * Default settings for each report type
 */
const DEFAULT_SETTINGS_BY_TYPE = {
  medical: {
    header: {
      enabled: true,
      backgroundColor: '#2980B9', // Blue
      textColor: '#FFFFFF',
      showLogo: true,
      showCompanyInfo: true,
      logoPosition: 'left', // left, center, right
      height: 30, // mm
      companyNameFontSize: 10,
      companyDetailsFontSize: 7,
      titleFontSize: 18
    },
    footer: {
      enabled: true,
      leftText: 'Confidential Medical Report',
      centerText: 'Generated by PACS System',
      rightText: 'Page {page} of {total}',
      showTimestamp: true,
      showPageNumbers: true,
      fontSize: 8,
      textColor: '#808080'
    },
    report: {
      title: 'RADIOLOGY REPORT',
      titleFontSize: 20,
      sectionFontSize: 12,
      contentFontSize: 10,
      margins: {
        top: 15,
        right: 15,
        bottom: 15,
        left: 15
      }
    }
  },
  statistical: {
    header: {
      enabled: true,
      backgroundColor: '#16A34A', // Green
      textColor: '#FFFFFF',
      showLogo: true,
      showCompanyInfo: true,
      logoPosition: 'left',
      height: 30,
      companyNameFontSize: 10,
      companyDetailsFontSize: 7,
      titleFontSize: 18
    },
    footer: {
      enabled: true,
      leftText: 'Internal Use Only',
      centerText: 'Statistical Report',
      rightText: 'Page {page} of {total}',
      showTimestamp: true,
      showPageNumbers: true,
      fontSize: 8,
      textColor: '#808080'
    },
    report: {
      title: 'STATISTICAL REPORT',
      titleFontSize: 20,
      sectionFontSize: 12,
      contentFontSize: 10,
      margins: {
        top: 15,
        right: 15,
        bottom: 15,
        left: 15
      }
    }
  },
  administrative: {
    header: {
      enabled: true,
      backgroundColor: '#7C3AED', // Purple
      textColor: '#FFFFFF',
      showLogo: true,
      showCompanyInfo: true,
      logoPosition: 'left',
      height: 30,
      companyNameFontSize: 10,
      companyDetailsFontSize: 7,
      titleFontSize: 18
    },
    footer: {
      enabled: true,
      leftText: 'Administrative Report',
      centerText: 'Generated by PACS System',
      rightText: 'Page {page} of {total}',
      showTimestamp: true,
      showPageNumbers: true,
      fontSize: 8,
      textColor: '#808080'
    },
    report: {
      title: 'ADMINISTRATIVE REPORT',
      titleFontSize: 20,
      sectionFontSize: 12,
      contentFontSize: 10,
      margins: {
        top: 15,
        right: 15,
        bottom: 15,
        left: 15
      }
    }
  },
  custom: {
    header: {
      enabled: true,
      backgroundColor: '#64748B', // Slate
      textColor: '#FFFFFF',
      showLogo: true,
      showCompanyInfo: true,
      logoPosition: 'left',
      height: 30,
      companyNameFontSize: 10,
      companyDetailsFontSize: 7,
      titleFontSize: 18
    },
    footer: {
      enabled: true,
      leftText: '',
      centerText: 'Generated by PACS System',
      rightText: 'Page {page} of {total}',
      showTimestamp: true,
      showPageNumbers: true,
      fontSize: 8,
      textColor: '#808080'
    },
    report: {
      title: 'REPORT',
      titleFontSize: 20,
      sectionFontSize: 12,
      contentFontSize: 10,
      margins: {
        top: 15,
        right: 15,
        bottom: 15,
        left: 15
      }
    }
  }
};

/**
 * Default report settings (medical type)
 */
const DEFAULT_SETTINGS = DEFAULT_SETTINGS_BY_TYPE.medical;

/**
 * Get report settings for specific type
 */
export const getReportSettings = (reportType = REPORT_TYPES.MEDICAL) => {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      const allSettings = JSON.parse(stored);
      const settings = allSettings[reportType];
      
      if (settings) {
        const defaults = DEFAULT_SETTINGS_BY_TYPE[reportType] || DEFAULT_SETTINGS;
        // Merge with defaults to ensure all fields exist
        return {
          header: { ...defaults.header, ...settings.header },
          footer: { ...defaults.footer, ...settings.footer },
          report: { ...defaults.report, ...settings.report }
        };
      }
    }
    
    // Return defaults for this type
    return DEFAULT_SETTINGS_BY_TYPE[reportType] || DEFAULT_SETTINGS;
  } catch (error) {
    console.error('[ReportSettings] Failed to load settings:', error);
    return DEFAULT_SETTINGS_BY_TYPE[reportType] || DEFAULT_SETTINGS;
  }
};

/**
 * Get all report settings (all types)
 */
export const getAllReportSettings = () => {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      return JSON.parse(stored);
    }
    return DEFAULT_SETTINGS_BY_TYPE;
  } catch (error) {
    console.error('[ReportSettings] Failed to load all settings:', error);
    return DEFAULT_SETTINGS_BY_TYPE;
  }
};

/**
 * Save report settings for specific type
 */
export const saveReportSettings = (reportType, settings) => {
  try {
    const allSettings = getAllReportSettings();
    allSettings[reportType] = settings;
    localStorage.setItem(STORAGE_KEY, JSON.stringify(allSettings));
    console.log('[ReportSettings] Settings saved for type:', reportType);
    return { success: true };
  } catch (error) {
    console.error('[ReportSettings] Failed to save settings:', error);
    return { success: false, error: error.message };
  }
};

/**
 * Save all report settings (all types)
 */
export const saveAllReportSettings = (allSettings) => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(allSettings));
    console.log('[ReportSettings] All settings saved');
    return { success: true };
  } catch (error) {
    console.error('[ReportSettings] Failed to save all settings:', error);
    return { success: false, error: error.message };
  }
};

/**
 * Reset to default settings
 */
export const resetReportSettings = () => {
  try {
    localStorage.removeItem(STORAGE_KEY);
    console.log('[ReportSettings] Settings reset to default');
    return { success: true };
  } catch (error) {
    console.error('[ReportSettings] Failed to reset settings:', error);
    return { success: false, error: error.message };
  }
};

/**
 * Get company profile from main settings
 */
export const getCompanyProfile = () => {
  try {
    const stored = localStorage.getItem('companyProfile');
    if (stored) {
      return JSON.parse(stored);
    }
    return {
      name: 'Medical Center',
      address: '123 Medical Street, City, State 12345',
      phone: '+1 (555) 123-4567',
      email: 'info@medicalcenter.com',
      website: '',
      logoUrl: ''
    };
  } catch (error) {
    console.error('[ReportSettings] Failed to load company profile:', error);
    return {
      name: 'Medical Center',
      address: '',
      phone: '',
      email: '',
      website: '',
      logoUrl: ''
    };
  }
};

/**
 * Export settings as JSON
 */
export const exportSettings = () => {
  const settings = getReportSettings();
  const blob = new Blob([JSON.stringify(settings, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `report-settings-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
};

/**
 * Import settings from JSON
 */
export const importSettings = (file) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const settings = JSON.parse(e.target.result);
        saveReportSettings(settings);
        resolve(settings);
      } catch (error) {
        reject(new Error('Invalid settings file'));
      }
    };

    reader.onerror = () => {
      reject(new Error('Failed to read file'));
    };

    reader.readAsText(file);
  });
};

export default {
  REPORT_TYPES,
  getReportSettings,
  getAllReportSettings,
  saveReportSettings,
  saveAllReportSettings,
  resetReportSettings,
  getCompanyProfile,
  exportSettings,
  importSettings,
  DEFAULT_SETTINGS,
  DEFAULT_SETTINGS_BY_TYPE
};
