
import logging
import re
from typing import List, Dict, Any, Optional
from sqlalchemy import text
from app.database import get_read_db

logger = logging.getLogger(__name__)

class SmartQueryService:
    """
    Service for executing safe, read-only SQL queries generated by AI.
    """

    # Simplified schema context for the LLM
    SCHEMA_CONTEXT = """
    Database Schema (PostgreSQL):
    
    1. patients
       - id (uuid, pk)
       - patient_id_local (varchar, unique) - MRN / Patient ID
       - medical_record_number (varchar)
       - patient_name (varchar)
       - sex (varchar)
       - birth_date (date)
       - created_at (timestamp)

    2. studies
       - id (uuid, pk)
       - patient_id (uuid, fk -> patients.id)
       - study_instance_uid (varchar, unique)
       - study_date (date)
       - study_time (varchar)
       - accession_number (varchar)
       - modality_primary (varchar) - e.g., CT, MR, CR, US
       - study_description (varchar)
       - referring_physician (varchar)
       - performing_physician (varchar)
       - institution_name (varchar)

    3. series
       - id (uuid, pk)
       - study_id (uuid, fk -> studies.id)
       - series_instance_uid (varchar, unique)
       - series_number (integer)
       - modality (varchar)
       - series_description (varchar)
       - number_of_instances (integer)
       
    4. instances
       - id (uuid, pk)
       - series_id (uuid, fk -> series.id)
       - sop_instance_uid (varchar, unique)
       - instance_number (integer)
       - file_path (varchar)
       - file_size (integer)

    5. orders
       - id (uuid, pk)
       - order_number (varchar)
       - accession_number (varchar)
       - patient_id (varchar) - MRN
       - patient_name (varchar)
       - modality (varchar)
       - procedure_code (varchar)
       - procedure_description (text)
       - status (varchar) - values: 'scheduled', 'in_progress', 'completed', 'cancelled', 'rescheduled', 'DELETED'
       - priority (varchar) - e.g., ROUTINE, URGENT, STAT
       - scheduled_at (timestamp)
       - created_at (timestamp)
       - completed_at (timestamp)
       - referring_doctor (varchar)
       - ordering_provider_name (varchar)

    Relationships:
    patients --(1:N)--> studies --(1:N)--> series --(1:N)--> instances
    orders --(1:1/N)--> studies (via accession_number)
    """

    FORBIDDEN_KEYWORDS = [
        "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE", 
        "GRANT", "REVOKE", "EXECUTE", "COMMIT", "ROLLBACK", 
        "CREATE", "REPLACE", "COMMENT", "LOCK", "Explain", "ANALYZE"
    ]

    @staticmethod
    def get_schema_context() -> str:
        """Return the schema definition for AI context."""
        return SmartQueryService.SCHEMA_CONTEXT

    @staticmethod
    def validate_sql(sql: str) -> bool:
        """
        Validate that the SQL is a safe SELECT statement.
        """
        cleaned_sql = sql.strip().upper()
        
        # Must start with SELECT
        if not cleaned_sql.startswith("SELECT"):
            logger.warning("SQL validation failed: Query must start with SELECT")
            return False
            
        # Check for forbidden keywords
        # We use word boundaries to avoid false positives (e.g. "update_date" field)
        for keyword in SmartQueryService.FORBIDDEN_KEYWORDS:
            pattern = r'\b' + keyword + r'\b'
            if re.search(pattern, cleaned_sql):
                logger.warning(f"SQL validation failed: Forbidden keyword '{keyword}' found")
                return False
                
        # Check for multiple statements (semicolon)
        # Allow trailing semicolon but not inside query
        if ";" in cleaned_sql[:-1]:
            logger.warning("SQL validation failed: Multiple statements not allowed")
            return False
            
        return True

    @staticmethod
    def execute_query(sql: str) -> List[Dict[str, Any]]:
        """
        Execute a read-only SQL query safely.
        """
        if not SmartQueryService.validate_sql(sql):
            raise ValueError("Invalid or unsafe SQL query. Only SELECT statements are allowed.")

        try:
            # Use get_read_db generator
            db_gen = get_read_db()
            db = next(db_gen)
            
            try:
                logger.info(f"Executing AI SQL: {sql}")
                result = db.execute(text(sql))
                
                # Convert rows to list of dicts
                columns = result.keys()
                rows = [dict(zip(columns, row)) for row in result.fetchall()]
                
                return rows
            finally:
                # Ensure connection is closed/returned to pool
                try:
                    next(db_gen)
                except StopIteration:
                    pass
                    
        except Exception as e:
            logger.error(f"SQL execution error: {e}")
            raise e
